-- Export Tools
-- Time: 2024-04-16 15:31:01
-- Service: s3989i.yz.db.inner-dmall.com:3989   Database: search_order_puredata
-- ------------------------------------------------------

/******************************************/
/*   DatabaseName = search_order_puredata   */
/*   TableName = wm_order   */
/******************************************/
CREATE TABLE `wm_order` (
  `id` bigint(20) NOT NULL,
  `source_order_id` bigint(20) DEFAULT NULL COMMENT '原订单号',
  `webuser_id` bigint(20) NOT NULL,
  `pin` varchar(45) DEFAULT NULL COMMENT '用户pin',
  `payment_type` int(11) NOT NULL COMMENT '支付方式',
  `online_payment_type` varchar(20) DEFAULT NULL COMMENT '在线支付方式',
  `shop_id` bigint(20) DEFAULT NULL COMMENT '商家内部门店编号（废弃）',
  `shop_name` varchar(100) NOT NULL COMMENT ' 门店名称',
  `shipment_type` int(4) NOT NULL COMMENT '配送方式',
  `shipment_date` date DEFAULT NULL COMMENT '订单配送日期，格式为yyyy-MM-dd',
  `shipment_option` int(4) DEFAULT NULL COMMENT '配送方式对应选项',
  `order_type` int(4) NOT NULL COMMENT '订单类型',
  `order_origin` int(4) NOT NULL COMMENT '订单来源',
  `invoice_flag` tinyint(1) NOT NULL COMMENT '开票类型',
  `invoice_title` varchar(45) NOT NULL COMMENT '发票抬头',
  `invoice_content` varchar(200) NOT NULL COMMENT '发票内容的值',
  `freight_fee` bigint(8) NOT NULL DEFAULT '0' COMMENT '运费',
  `use_coupon` bigint(8) NOT NULL DEFAULT '0' COMMENT '使用优惠劵优惠金额',
  `use_coupon_id` varchar(50) DEFAULT '' COMMENT '优惠券id',
  `use_card` bigint(8) NOT NULL DEFAULT '0',
  `use_card_id` varchar(50) DEFAULT '',
  `use_balance` bigint(10) NOT NULL DEFAULT '0' COMMENT '使用余额支付金额',
  `promotion_id` bigint(14) DEFAULT NULL COMMENT '废弃字段',
  `promotion_price` bigint(14) NOT NULL DEFAULT '0' COMMENT '订单促销优惠总优惠',
  `ware_total_price` bigint(14) NOT NULL DEFAULT '0' COMMENT '商品总额',
  `total_price` bigint(14) NOT NULL DEFAULT '0' COMMENT '订单金额',
  `order_price` bigint(14) NOT NULL DEFAULT '0' COMMENT '订单最终实付金额',
  `order_status` int(11) NOT NULL COMMENT '订单状态',
  `status_code` int(11) DEFAULT NULL COMMENT '订单状态编码,大部分时候与order_status相同,而取消存在多种状态',
  `return_status` int(11) DEFAULT NULL COMMENT '废弃字段',
  `refund_flag` int(11) DEFAULT NULL COMMENT '废弃字段',
  `order_pay_time` datetime DEFAULT NULL COMMENT '订单支付完成时间',
  `order_cancel_time` datetime DEFAULT NULL COMMENT '订单取消时间/预计未支付取消时间',
  `order_complete_time` datetime DEFAULT NULL COMMENT '订单完成时间',
  `user_ip` varchar(15) NOT NULL COMMENT '用户下单Ip地址\n',
  `order_sn` varchar(50) DEFAULT NULL COMMENT '订单流水号,目前仅为线下订单使用',
  `sent_flag` int(11) DEFAULT '-1' COMMENT '废弃字段',
  `financial_status` tinyint(4) DEFAULT '0' COMMENT '财务状态：1，对账完成',
  `comment_num` int(11) DEFAULT '0' COMMENT '订单评论次数',
  `remarks` varchar(150) DEFAULT NULL COMMENT '订单备注',
  `properties` varchar(2000) DEFAULT NULL COMMENT '订单金额相关字段，json格式字符串',
  `created` datetime(3) DEFAULT NULL,
  `modified` datetime NOT NULL,
  `yn` tinyint(1) NOT NULL DEFAULT '1',
  `vender_id` int(11) DEFAULT NULL COMMENT '商家ID',
  `vender_name` varchar(100) DEFAULT NULL COMMENT '商家名称',
  `erp_store_id` int(11) DEFAULT NULL COMMENT '门店ID',
  `order_main_mark` varchar(50) DEFAULT NULL COMMENT '系统调用标识',
  `self_code` varchar(10) DEFAULT NULL COMMENT '自提码',
  `display_status` tinyint(4) DEFAULT NULL COMMENT '用户可见标识',
  `payment_trade_num` varchar(200) DEFAULT NULL COMMENT '第三方平台交易号码',
  `order_sku_type` tinyint(4) DEFAULT NULL COMMENT '订单商品类型',
  `invoice_type` varchar(50) DEFAULT NULL COMMENT '发票类型',
  `order_create_time` datetime DEFAULT NULL COMMENT '订单下单时间',
  `shipment_time` varchar(40) DEFAULT NULL COMMENT '配送/自提时间，格式为HH:mm-HH:mm',
  `offline_pay_cash` bigint(14) DEFAULT '0' COMMENT '线下订单选择在线支付方式时，线下支付的部分现金金额，线上订单或线下订单选择货到付款时该值为0',
  `sale_type` tinyint(4) DEFAULT '1' COMMENT '销售类型',
  `order_tag` varchar(2000) DEFAULT NULL COMMENT '订单业务扩展标记，json格式字符串',
  `coupon_code` varchar(255) DEFAULT NULL COMMENT '优惠码code',
  `coupon_code_amount` int(11) DEFAULT NULL COMMENT '优惠码金额',
  `versions` tinyint(3) DEFAULT '1' COMMENT '订单版本号，新建订单时默认为1，修改订单后累加',
  `use_dps_card_fee` bigint(10) DEFAULT '0' COMMENT '全球精选卡使用金额',
  `ware_tag` int(10) DEFAULT '0' COMMENT '订单下商品标签集，以二进制位表示的整数',
  `split_times` tinyint(2) DEFAULT '0' COMMENT '订单拆分次数，拆分一次，父单拆分次数加1',
  `parent_id` bigint(20) DEFAULT '0' COMMENT '父单ID',
  `lock_type` tinyint(2) DEFAULT '0' COMMENT '锁单类型LockTypeEnum，0：未锁定',
  `unique_id` varchar(100) DEFAULT NULL COMMENT '订单唯一标识，客户端传递的uuid串，用户防重，该字段需要创建唯一索引(unique index)',
  `trade_type` varchar(50) DEFAULT NULL COMMENT '结算类型',
  `custom_tag` varchar(2000) DEFAULT NULL COMMENT '订单自定义扩展标记，json格式字符串',
  `ship_start_time` datetime DEFAULT NULL COMMENT '配送预计开始时间',
  `ship_end_time` datetime DEFAULT NULL COMMENT '配送预计结束时间',
  `external_store_code` varchar(100) DEFAULT NULL COMMENT '外部商家的门店编号',
  `payment_detail` varchar(1000) DEFAULT NULL COMMENT '订单支付明细',
  `auto_prevention_time` datetime DEFAULT NULL COMMENT '自动防损时间',
  `offline_coupon_detail` varchar(500) DEFAULT NULL COMMENT '线下订单使用优惠券明细',
  `third_party_order_id` varchar(100) DEFAULT NULL COMMENT '三方平台下单订单号',
  `dmall_coupon_detail` varchar(500) DEFAULT NULL COMMENT '多点券使用明细',
  `data_version` int(11) DEFAULT '0' COMMENT '订单数据非兼容变更版本号',
  `lucky_cut_detail` varchar(500) DEFAULT NULL COMMENT '随机减使用明细',
  `promotion_detail` varchar(1000) DEFAULT NULL COMMENT '促销优惠使用明细',
  `virtual_card_detail` varchar(1000) DEFAULT NULL COMMENT '虚拟卡明细',
  `sub_order_detail` json DEFAULT NULL COMMENT '子单明细',
  `modified_version` bigint(255) DEFAULT '0' COMMENT '数据更新版本号',
  `dmall_coupon_detail_new` json DEFAULT NULL COMMENT '多点券使用明细新',
  PRIMARY KEY (`id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_order_create_time` (`order_create_time`),
  KEY `idx_created` (`created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/******************************************/
/*   DatabaseName = search_order_puredata   */
/*   TableName = wm_order_consignee   */
/******************************************/
CREATE TABLE `wm_order_consignee` (
  `id` bigint(20) NOT NULL COMMENT '订单系统分表的ID',
  `order_id` bigint(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `email` varchar(80) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  `area_id` int(8) NOT NULL,
  `longitude` double(10,7) DEFAULT NULL COMMENT '坐标经度',
  `latitude` double(10,7) DEFAULT NULL COMMENT '坐标纬度',
  `address_prefix` varchar(1000) DEFAULT '' COMMENT '市级区级地址快照',
  `address_detail` varchar(1000) DEFAULT NULL,
  `address_id` bigint(20) DEFAULT NULL,
  `address_position` varchar(50) DEFAULT NULL,
  `properties` json DEFAULT NULL,
  `order_create_time` datetime DEFAULT NULL COMMENT '订单下单时间',
  `created` datetime(3) NOT NULL,
  `modified` datetime(3) NOT NULL,
  `yn` tinyint(1) NOT NULL,
  `webuser_id` bigint(20) DEFAULT NULL,
  `address_ext_info` json DEFAULT NULL COMMENT '收货地址扩展字段，保存结构化的地址数据，如一二三级地址',
  `id_card` varchar(150) DEFAULT NULL COMMENT '收货人身份证号码',
  `pid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pid`),
  KEY `fk_order_id_idx` (`order_id`),
  KEY `consignee_area_id_fk_idx` (`area_id`)
) ENGINE=InnoDB AUTO_INCREMENT=18312578922 DEFAULT CHARSET=utf8;


/******************************************/
/*   DatabaseName = search_order_puredata   */
/*   TableName = wm_order_ware   */
/******************************************/
CREATE TABLE `wm_order_ware` (
  `id` bigint(20) NOT NULL COMMENT '订单系统分表的ID',
  `order_id` bigint(20) NOT NULL,
  `shop_id` bigint(20) DEFAULT NULL COMMENT '商家内部门店编号（废弃）',
  `sku_id` bigint(20) NOT NULL,
  `wm_sku_id` bigint(20) DEFAULT NULL COMMENT '物美商品sku',
  `ware_id` bigint(20) DEFAULT NULL,
  `wm_ware_id` bigint(20) DEFAULT NULL COMMENT '物美商品id',
  `matnr` varchar(100) DEFAULT NULL,
  `ware_weight` float DEFAULT '0',
  `order_create_time` datetime DEFAULT NULL COMMENT '订单下单时间',
  `ware_name` varchar(200) NOT NULL,
  `ware_img_url` varchar(500) DEFAULT NULL,
  `item_num` varchar(50) NOT NULL DEFAULT '0',
  `ware_num` int(8) NOT NULL,
  `offline_num` decimal(12,4) DEFAULT NULL COMMENT '线下推送订单的商品数量(支持浮点数,可能是0.6千克，可以精确到0.0001kg)',
  `ware_type` int(4) DEFAULT NULL COMMENT '商品类型\n1：普通\n2：赠品\n3：附件',
  `ware_price` bigint(12) NOT NULL COMMENT '商品价格',
  `promotion_price` bigint(12) DEFAULT '0' COMMENT '促销优惠',
  `promotion_id` varchar(1000) DEFAULT NULL COMMENT '该商品参与的所有促销ID，多个值逗号隔开',
  `properties` varchar(2000) DEFAULT NULL COMMENT '订单商品扩展字段',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `yn` tinyint(1) NOT NULL,
  `sku_type` tinyint(4) DEFAULT NULL COMMENT '商品类型(1:标品,2:散卖)',
  `promotion_price_list` varchar(1000) DEFAULT NULL COMMENT '该商品参与的所有促销金额，多个字用(,)隔开',
  `promotion_type` varchar(1000) DEFAULT NULL COMMENT '该商品参与的所有促销类型，多个类型用逗号(,)隔开',
  `coupon_amount` bigint(8) DEFAULT NULL COMMENT '优惠券平分到每个商品上面的金额',
  `invoice_type` varchar(50) DEFAULT NULL COMMENT '发票类型',
  `source_ware_id` bigint(20) DEFAULT NULL COMMENT '修改订单中，本商品记录在原订单商品表中的ID',
  `webuser_id` bigint(20) DEFAULT NULL,
  `coupon_code_amount` int(11) DEFAULT NULL COMMENT '优惠码分摊到每个商品上的金额',
  `catagory_id` varchar(100) DEFAULT NULL COMMENT '商品品类ID',
  `ware_tag` int(10) DEFAULT '0' COMMENT '商品标签，以二进制位表示的整数',
  `custom_tag` varchar(2000) DEFAULT NULL COMMENT '商品自定义扩展标记',
  `matkl` varchar(20) DEFAULT NULL COMMENT '商品线下品类id，多个用逗号隔开',
  `offline_bar_code` varchar(100) DEFAULT NULL COMMENT '商品条形码，多个用逗号隔开',
  `promotion_sub_type` varchar(1000) DEFAULT NULL COMMENT '促销子类型',
  `ware_promotion_price` bigint(12) DEFAULT NULL COMMENT '商品促销后的单价',
  `offline_coupon_amount` bigint(255) DEFAULT '0' COMMENT '商家券分摊金额',
  `dmall_coupon_detail` varchar(500) DEFAULT NULL COMMENT '多点券使用明细',
  `offline_coupon_detail` varchar(500) DEFAULT NULL COMMENT '商家券使用明细',
  `lucky_cut_detail` varchar(500) DEFAULT NULL COMMENT '随机减使用明细',
  `promotion_detail` varchar(2000) DEFAULT NULL COMMENT '促销优惠明细',
  `payment_detail` varchar(1000) DEFAULT NULL COMMENT '商品支付明细',
  `dmall_coupon_detail_new` json DEFAULT NULL COMMENT '多点券使用明细新',
  `pid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pid`),
  KEY `order_id_idx` (`order_id`),
  KEY `idx_created` (`created`)
) ENGINE=InnoDB AUTO_INCREMENT=65505292842 DEFAULT CHARSET=utf8;

