package com.bibabo.flink.wordcount.socket;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;

public class FlinkSocketServer {

    private static final Logger log = LoggerFactory.getLogger(FlinkSocketServer.class);

    public static void main(String[] args) throws IOException {



        // 创建服务器Socket，监听8080端口
        ServerSocket serverSocket = new ServerSocket(8080);
        log.info("Flink测试数据服务器已启动，等待连接...");

        // 接受客户端连接
        Socket clientSocket = serverSocket.accept();
        log.info("Flink客户端已连接: " + clientSocket.getInetAddress() + "端口：" + clientSocket.getPort());

        PrintWriter out = new PrintWriter(clientSocket.getOutputStream(), true);
        Scanner scanner = new Scanner(System.in);

        log.info("输入模式选择: 1-自动生成测试数据 2-手动输入数据");
        int mode = scanner.nextInt();
        scanner.nextLine(); // 消耗换行符

        if (mode == 1) {
            // 自动生成测试数据模式
            autoGenerateData(out);
        } else {
            // 手动输入模式
            manualInputData(out, scanner);
        }

        // 关闭资源
        out.close();
        clientSocket.close();
        serverSocket.close();
        log.info("服务器已关闭");
    }

    private static void autoGenerateData(PrintWriter out) {

        String[] words = {"apple", "banana", "orange", "grape", "watermelon",
                "flink", "stream", "processing", "big", "data"};

        try {
            while (true) {
                // 随机选择一个单词发送
                String word = words[(int) (Math.random() * words.length)];
                out.println(word);
                log.info("已发送: " + word);

                // 每秒发送一条数据
                TimeUnit.SECONDS.sleep(1);
            }
        } catch (InterruptedException e) {
            log.info("数据发送被中断");
        }
    }

    private static void manualInputData(PrintWriter out, Scanner scanner) {
        log.info("请输入要发送的数据(输入exit退出):");
        while (true) {
            String line = scanner.nextLine();
            if ("exit".equalsIgnoreCase(line)) {
                break;
            }
            out.println(line);
        }
    }
}